---
title: "DS2_midterm"
author: "My An Huynh, Soomin You"
date: "`r Sys.Date()`"
output: github_document
---

```{r}
library(tidyverse)
library(MASS)
library(caret)
library(corrplot)
library(mgcv)
```

## Load Data
```{r}
load("data/dat1.RData")
load("data/dat2.RData")
```

## Summary Statistics 
## Exploratory Data Analysis 
```{r}
train = dat1 |>
  dplyr::select(-id)


test = dat2 |> 
  dplyr::select(-id)

train2 = dat1 |> 
  dplyr::select(-id) |>
  mutate(
    gender = as.numeric(gender), 
    race = as.numeric(race), 
    smoking = as.numeric(smoking), 
    diabetes = as.numeric(diabetes)
  )
  

x = model.matrix(log_antibody ~ ., data = train)[, -1]
y = train$log_antibody

x2 = model.matrix(log_antibody ~ ., data = train2)[, -1]
y2 = train2$log_antibody

featurePlot(x = train[, -c(2,3,4,8,9, 13)], y = train$log_antibody, plot = "scatter")

#  boxplot for factor/binary variables 
ggplot(aes(x = factor(gender), y = log_antibody), data = train) + 
  geom_boxplot()
ggplot(aes(x = factor(race), y = log_antibody), data = train) + 
  geom_boxplot()
ggplot(aes(x = factor(race), y = log_antibody), data = train) + 
  geom_boxplot()
ggplot(aes(x = factor(diabetes), y = log_antibody), data = train) + 
  geom_boxplot()
ggplot(aes(x = factor(hypertension), y = log_antibody), data = train) + 
  geom_boxplot()
ggplot(aes(x = factor(smoking), y = log_antibody), data = train) + 
  geom_boxplot()


corrplot(cor(x), method = "circle", type = "full")

test = dat2 |> 
  dplyr::select(-id)

x_test = model.matrix(log_antibody ~ ., data = test)[, -1]
y_test = train$log_antibody
```


## Model training 
1) elastic net  
2) MARS 
3) PCR
4) GAM
5) PLS

```{r pcr}
# pcr model 
pcr_mod = train(x = x,
                y = y, 
                method = "pcr", 
                tuneGrid = data.frame(ncomp = 1:15), 
                trControl = ctrl1, 
                preProcess = c("center", "scale"))
summary(pcr_mod)
```


```{r gam}
set.seed(1)
# gam model 
ctrl1 = trainControl(method = "cv", number = 10)

gam_mod = train(x = x, 
                y = y, 
                method = "gam", 
                trControl = ctrl1)

gam_mod$bestTune
gam_mod$finalModel

summary(gam_mod)
```


```{r pls}
set.seed(1)
# pls model 
pls_mod = train(x = x,
                y = y, 
                method = "pls", 
                tuneGrid = data.frame(ncomp = 1:15), 
                trControl = ctrl1, 
                preProcess = c("center", "scale"))
summary(pls_mod)

# test error 
pred_pls = predict(pls_mod, newdata = x_test)
mean((y_test - pred_pls)^2)

ggplot(pls_mod, highlight = TRUE)
```

```{r elastic_net}
set.seed(1)
enet_mod = train(log_antibody ~ ., 
                 data = train,
                 method = "glmnet", 
                 tuneGrid = expand.grid(alpha = seq(0, 1, length = 21), 
                                        lambda = exp(seq(6, 0, length = 100))),
                 trControl = ctrl1)

enet_mod$bestTune
```

```{r mars}
set.seed(1)
mars_mod = train(x = x, 
                 y = y, 
                 method = "earth", 
                 trControl = ctrl1)

summary(mars_mod)
```



## Model validation 
6) comparison 
```{r}
resamp = resamples(list(MARS = mars_mod, 
                      GAM = gam_mod,
                      enet = enet_mod, 
                      pls = pls_mod))
       
summary(resamp)
bwplot(resamp, metric = "RMSE")
```



## Conclusion 

